### PR TITLE
Added mailgun example (#52)

### PR DESCRIPTION
**Pull request by xementor**
Issue: https://github.com/triggerdotdev/api-reference/issues/52

### Summary
Send email via mailgun

### Screen record
[mailgun_record](https://drive.google.com/file/d/1WdudliUM2Tbb4aa7UcWQjL4Le9rhkg1C/view?usp=sharing)

### CODE REVIEW

**Comment by D-K-P** [comment]
Hey @xementor you need to include screenshots of a successful run on all your PRs

**Comment by D-K-P** [comment]
@xementor sorry I missed your video link!

username: process.env.MAILGUN_API_TOKEN,

Is this a username or API token? What should the value be here

**Comment by xementor** [comment]
@D-K-P in there dashboard 
the key id used as username in the code
m
for the username -> the api_key_id
and for key -> generated private key when creating this api_key_id

```
const mg = mailgun.client({
  username: process.env.MAILGUN_API_TOKEN,
  key: process.env.MAILGUN_PRIVATE_API_KEY,
});
```

so what should i use for the environment variable naming. 

I have checked the video link, it can view by anyone. so please recheck.

**Comment by D-K-P** [comment]
@xementor so:

change username to "apiKeyId: process.env.MAILGUN_API_KEY_ID'
and key is fine. Thanks!

**Comment by D-K-P** [comment]
@xementor if you fix conflicts I'll merge this one - thank you!

**Comment by xementor** [comment]
@D-K-P 

changing username to apiKeyId won't work
as in their docs 
image
they want username.

so i just changed the env variable to MAILGUN_API_KEY_ID

**Comment by D-K-P** [comment]
@xementor - my mistake, have merged. Thank you!

**Pull request merged**
