### PR TITLE
Added Gmail example job (#1)

### PR DESCRIPTION
**Pull request by biplobsd**
Issues: #1

## Description
I use OAuth for authenticating the Gmail API. I tried using a service account, but I getting an error every time: `precondition check failed`. I researched this issue but couldn't find a solution. Then, I switched to OAuth, and everything worked fine.

I have created an example for sending gmail. It triggers with object fields `to`, `subject`, and `message`, and this email will be sent using the Google Gmail API.

## Screen record
[send-gmail.webm](https://github.com/triggerdotdev/api-reference/assets/43641536/aff092d4-a14c-49a0-b0e1-1b12b4e6612f)

### CODE REVIEW

**Comment by D-K-P** [comment]
OK so I managed to get this working using the JWT - this is important because these examples have to be one code file only.

These are the steps which enabled me to do it, you have to set up domain-wide delegation in order to be able to send emails from gmail:

**Setting up Domain-Wide Delegation:**
1. Google Admin Console: Go to your [Google Admin Console](https://admin.google.com/).
2. Security Settings: Navigate to Security > API controls.
3. Manage Domain-Wide Delegation: In the "Domain wide delegation" panel, click on "Manage Domain-Wide Delegation".
4. Add Service Account: Click on "Add new" and provide:
5. Client ID: This is the Service Account's Client ID, which can be found in your Google Cloud Console under the Service Account's details.
6. OAuth Scopes: Enter https://www.googleapis.com/auth/gmail.send to grant send permissions via Gmail.
Click on "Authorize".

You then need to add the impersonation email (a verified one for the domain), which is the person who will be sending the emails (This is how you stop the `precondition check failed error`).:

```ts
// Create a JWT (JSON Web Token) authentication instance for Google APIs.
const auth = new JWT({
  email: process.env.CLIENT_EMAIL, // The email associated with the service account
  key: process.env.PRIVATE_KEY!.split(String.raw`\n`).join("\n"), // The private key associated with the service account
  scopes: ["https://www.googleapis.com/auth/gmail.send"], // The desired scope for sending Gmail messages
});

// Replace with the email of the user you're impersonating (the user that will send the email)
auth.subject = process.env.IMPERSONATION_EMAIL; 

// Initialize the Gmail API
const gmail = google.gmail({ version: "v1", auth });
```

Could you change it to use this please, with detailed instructions on how to set it up in the comments, then I'll merge it. Thank you!

**Comment by biplobsd** [comment]
@D-K-P I don't have google workspace account. So I'm unable to test this code 😢

**Comment by biplobsd** [comment]
@D-K-P, Here is the code for sending mail with service account authentication. I'm confused in the `subject` and `userId` field is the need to same or not?

```typescript
import { TriggerClient, eventTrigger } from "@trigger.dev/sdk";
import { google } from "googleapis";
import { JWT } from "google-auth-library";
import z from "zod";

const client = new TriggerClient({
  id: "api-reference",
});

// Create a service account and project: https://cloud.google.com/iam/docs/service-account-overview
// Create a JWT (JSON Web Token) authentication instance for Google APIs.
// https://cloud.google.com/nodejs/docs/reference/google-auth-library/latest/google-auth-library/jwt
const auth = new JWT({
  email: process.env.CLIENT_EMAIL, // The email associated with the service account
  key: process.env.PRIVATE_KEY!.split(String.raw`\n`).join("\n"), // The private key associated with the service account
  scopes: ["https://www.googleapis.com/auth/gmail.send"], // The desired scope for accessing Google Sheets
});

// Replace with the email of the user you're impersonating (the user that will send the email)
auth.subject = process.env.IMPERSONATION_EMAIL;

// Create a Gmail API instance
const gmail = google.gmail({ version: "v1", auth: auth });

client.defineJob({
  id: "send-gmail",
  name: "Send Gmail",
  version: "1.0.0",
  trigger: eventTrigger({
    name: "send-gmail",
    schema: z.object({
      to: z.string(),
      subject: z.string(),
      message: z.string(),
    }),
  }),
  run: async (payload, io, ctx) => {
    const { to, subject, message } = payload;

    // Wrap an SDK call in io.runTask so it's resumable and displays in logs
    await io.runTask(
      "Send Gmail",
      async () => {
        // Create the email message
        const email = `To: ${to}\r\nSubject: ${subject}\r\n\r\n${message}`;

        // Send the email
        await gmail.users.messages.send({
          userId: "me",
          requestBody: {
            raw: Buffer.from(email).toString("base64"),
          },
        });
      },
      { name: "Send Gmail", icon: "google" }
    );
  },
});

import { createExpressServer } from "@trigger.dev/express";
createExpressServer(client);
```

**Comment by biplobsd** [comment]
I'm closing OAuth

**Pull request closed without merging**
