### PR TITLE
Added example job using the Google Sheets API (#3)

### PR DESCRIPTION
**Pull request by biplobsd**
## Summary
I created Google sheets append row example. User trigger with `fullName` and `githubUrl` then this data will append in the spreadsheets.

## Screen record
[Google-Sheet-Example.webm](https://github.com/triggerdotdev/api-reference/assets/43641536/07ecea7d-b67a-4ed4-8b75-3c799651a8b6)

### CODE REVIEW

**Comment by biplobsd** [comment]
@D-K-P Kindly review 😊

**Comment by biplobsd** [comment]
@D-K-P Thanks 😁

**Comment by D-K-P** [comment]
@biplobsd I've amended the file:

https://github.com/triggerdotdev/api-reference/blob/main/src/google-sheets.ts

- TriggerClient should always go under the imports, and you don't need to set the key
- I added range to the zod schema
- I added a load more comments and links so it's easier for the user to understand when they're following along (this is important for these examples)

Great job. Will add you to the leaderboard.

**Comment by biplobsd** [comment]
@D-K-P I forgot to add GitHub environment variable in the .env.example file

 https://github.com/triggerdotdev/api-reference/blob/21e02088b28ac08e7cbcff956bbf1d7761944592/.env.example#L6

**Pull request merged**
