### PR TITLE
Added Shopify example (#4)

### PR DESCRIPTION
**Pull request by biplobsd**
Issue: #4

## Summary
I have created a shopify product variant price updater. Event trigger with `productVariantId` and `price` then this update using shopify sdk.

## Video recording
[shopify-example.webm](https://github.com/triggerdotdev/api-reference/assets/43641536/777e159b-75a6-4b8a-ab0d-ed12fdec0ff9)

### CODE REVIEW

**Comment by biplobsd** [comment]
Hi @D-K-P Have a look at my example and let me know if any changes are needed or not. 😊

**Comment by D-K-P** [comment]
This works. The only thing I'd add is some instructions on how to get your API keys because it's a bit buried, and then it's a great example, nice job.

**Comment by biplobsd** [comment]
@D-K-P Done, review again

**Comment by biplobsd** [comment]
@nicktrn Ok I'll be more user-friendly find out the approach. Thanks

**Pull request merged**
