### PR TITLE
Add Discord HTTP endpoint example

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
Closed: #84

### CODE REVIEW

**Comment by D-K-P** [comment]
Hey @rishi-raj-jain this needs to use` respondWith` instead to catch all requests and do verification in there

**Comment by rishi-raj-jain** [comment]
@D-K-P 

I'm working on this. May you please assign it to me?

**Comment by rishi-raj-jain** [comment]
Still working on this.

**Comment by rishi-raj-jain** [comment]
> You'll also need to do verification where it is currently as well because we require you to implement that

Can you explain this?

**Comment by rishi-raj-jain** [comment]
- Please find the whole Discord Interaction URL guide at: https://supabase.com/docs/guides/functions/examples/discord-bot
- I've authenticated the requests
- I've added an example to respond to Discord Interactions (that are the only thing that trigger HTTP POST requests from Discord)


https://github.com/triggerdotdev/api-reference/assets/46300090/7d08dfab-53d7-495f-bcf9-7f96ef0385e2

**Pull request merged**
