### PR TITLE
Added cal.com example job

### PR DESCRIPTION
**Pull request by gjohnsx**
I added a simple Cal.com API job that finds all bookings. It's so simple that it doesn't need a zod schema.

image

Here's a helpful Postman collection of Cal.com API examples: https://www.postman.com/calcom/workspace/cal-com-workspace/request/20666831-abb05c19-4615-48d4-b2be-4b440cd27f48

### CODE REVIEW

**Comment by D-K-P** [comment]
I can't get this one to work for some reason when using my API key - how did you generate it?

**Comment by gjohnsx** [comment]
> @gjohnsx I can't get this one to work for some reason when using my API key - how did you generate it?

hmm I just generated it in the developer settings with no expiration: 
image
image
Tested again just now and it is working.

Also what is the proper icon name I should use for the metadata?

**Comment by D-K-P** [comment]
@gjohnsx this is actually a problem with Cal.com. I created a new account and it worked. Could you leave this comment somewhere:

// If you get the error 'An error occurred while querying the database', this may because you have linked calendars in your account. This is a known Cal.com issue. Please reach out to us on Discord if you are having issues.

**Comment by gjohnsx** [comment]
@D-K-P Added that comment and a link to API reference.

**Pull request merged**
