### PR TITLE
feat: Added Notion Example (#45)

### LINKED ISSUE #45: Create an example job using the Notion API
## Overview:

While we build our official integrations, we want to create examples of how to create jobs which use other APIs with Trigger.dev. This reference will be used in the app on any service we don’t have an integration for yet.

## Details:

In this example, you will build a simple job which uses the Notion API. This will replace the GitHub example we currently have in the app:

## Requirements:

- Use the structure of our [GitHub API reference file](https://github.com/triggerdotdev/api-reference/blob/main/src/github.ts).
- The job must connect to the [Notion API](https://developers.notion.com/), using their official SDK, and return an example payload from the API.

## Guidelines:

- The job should use an `eventTrigger`.
- The job should use `zod` to define the payloads.
- Use native fetch where no official SDK or incompatible auth
- Only use `io.backgroundFetch()` where absolutely necessary
- Avoid external packages apart from official SDKs
- Prefer REST over GraphQL - avoid raw queries
- Use a minimal `io.runTask()` callback - initialise clients and auth in global scope if possible
- Leave clear comments with links to relevant developer docs, API key pages etc. [The Discord example](https://github.com/triggerdotdev/api-reference/blob/main/src/discord.ts) is the level of commenting we are looking for. 
​
## Required Structure:

1. Follow [this guide](https://github.com/triggerdotdev/api-reference#setup-how-to-use-this-repo) to get the project setup.​
2. Create a new file in the src folder, named to match the API (e.g. GitHub would be called github.ts).​
3. The Trigger.dev client must be defined at the top of the job, with the 'api-reference' id:

```ts
const client = new TriggerClient({ id: "api-reference" });
```
​
4. You must add the Express specific lines to the bottom of the Job file:
​
```ts
// These lines can be removed if you don't want to use express
import { createExpressServer } from "@trigger.dev/express";
createExpressServer(client);
```
​
5. You must add the new script to the package.json file, in this format:
​
```ts
"scripts": {
  //..other scripts
  "<api-name>": "nodemon --watch src/<api name>.ts -r tsconfig-paths/register -r dotenv/config src/<api name>.ts"
}
```

> [!IMPORTANT]
You must test this Job works before submitting your PR, including a screenshot of a successful run. This may involve you having to setup accounts with services.
>

### PR DESCRIPTION
**Pull request by nabinbhatt**
closes #45 

image
Screenshot
image

### CODE REVIEW

**Comment by D-K-P** [comment]
Hey @nabinbhatt looking good at a glance, little tweaks:

- Could you change the schema so that it is included inside `client.defineJob()`. You can look at the other jobs for reference on how to do that with zod.
- Could you add instructions on the scopes you need to add for the integration and how to set it up properly so it can read any page in your org 

Thank you!

**Comment by nabinbhatt** [comment]
@D-K-P please review

**Comment by D-K-P** [comment]
Hey @nabinbhatt you need to add a comment that the integration needs to be added as a ‘connection’ to the page, otherwise this job won’t work

**Comment by D-K-P** [comment]
This is great @nabinbhatt, i'm going to make some tiny tweaks but i'll merge it.

Could you DM me on Discord please (i'm D-K-P) so I can message you about swag. Thanks!

**Pull request merged**
