### PR TITLE
Added discord example (#37)

### PR DESCRIPTION
**Pull request by biplobsd**
closed: #37 

## Summary
Send message to the server using discord bot.

## Screen record
[discord-example.webm](https://github.com/triggerdotdev/api-reference/assets/43641536/48444693-9935-4769-9445-423f72081c31)

### CODE REVIEW

**Comment by nicktrn** [comment]
Thanks @biplobsd, I think we should use REST without WebSockets here. An [example](https://discord.js.org/docs/packages/core/1.0.1#:~:text=Independent%20REST%20API%20Usage).

**Comment by biplobsd** [comment]
Thanks @nicktrn look again..

**Comment by nicktrn** [comment]
Thanks, much simpler and serverless-friendly! Will leave actual testing to @D-K-P.

**Comment by D-K-P** [comment]
@biplobsd this great. I thought you'd end up using discordjs, not sure if there's another way. Also cheers @nicktrn

**Pull request merged**
