### PR TITLE
Added twitter example (#13)

### PR DESCRIPTION
**Pull request by biplobsd**
Issue: #13 

## Summary
I have created an example for posting tweet. 

## Screen recording
[twitter-example.webm](https://github.com/triggerdotdev/api-reference/assets/43641536/406c29be-d5cb-4cfd-b732-ecd3c63ba096)

### CODE REVIEW

**Comment by biplobsd** [comment]
@D-K-P Kindly review

**Comment by nicktrn** [comment]
Hey @biplobsd, good job working out those auth issues.

One concern with the `oauth-1.0a` package: It seems to be unmaintained. Then again, full typescript support, vs some of the alternatives. Seems to do the job.

More importantly though, I don't think we need to use `io.backgroundFetch()` here. Shouldn't we get an almost immediate response?

**Comment by D-K-P** [comment]
@nicktrn, i agree with that. @biplobsd could you make those changes please

**Comment by biplobsd** [comment]
> Hey @biplobsd, good job working out those auth issues.
> 
> One concern with the `oauth-1.0a` package: It seems to be unmaintained. Then again, full typescript support, vs some of the alternatives. Seems to do the job.
> 
> More importantly though, I think we can replace `io.backgroundFetch()` with native `fetch()`. Shouldn't we get an almost immediate response?
> 
> (Just a sidenote: You can use `io.backgroundFetch()` outside of `io.runTask()` to avoid unnecessary subtasks.)

@nicktrn I can't find any alternative for `oauth-1.0a` well maintain packages. Could you find me an alternative ?

**Comment by nicktrn** [comment]
> alternative for oauth-1.0a

None of the packages seem ideal, this is probably the best option for now. I recommend we leave it as is.

An alternative would be to write our own helper to include in the `integration-kit` - this is clearly out of scope here. But if we need OAuth 1.0 for other examples or even integrations, it may be required at some point.

NB: You should be able to use global `fetch()` after merging the latest changes from main.

**Comment by biplobsd** [comment]
@nicktrn @D-K-P Review again... 🚀

**Pull request merged**
