### PR TITLE
AWS SDK reference example

### PR DESCRIPTION
**Pull request by sp6370**
Fixes: https://github.com/triggerdotdev/api-reference/issues/36
Demo: https://www.loom.com/share/05d181a8396141bfa6c74be407da56ce

### CODE REVIEW

**Comment by sp6370** [comment]
@D-K-P Could you have a look?

**Comment by D-K-P** [comment]
Great work @sp6370. Reach out to me on Discord (D-K-P) and we can chat about your points :)

**Comment by sp6370** [comment]
@D-K-P I use a platform called opensauced to keep track of my OSS contributions. Would you mind assigning me for the PR so it shows up in opensauced. Apologies for the trouble.

**Comment by D-K-P** [comment]
@sp6370 not a problem that's done for you

**Pull request merged**
