### PR TITLE
Add Zapier HTTP endpoint example

### LINKED ISSUE #96: Create an example Zapier job which uses an HTTP endpoint / trigger
### Overview

HTTP endpoints allow you to subscribe to changes from an API. You can use `defineHttpEndpoint` to receive webhooks, verify them, and create an HTTP Trigger.

### Details:

The task is to create a job example which is triggered by an HTTP Trigger when a change is received from Zapier.

Reference material:

- Read our [HTTP endpoints docs](https://trigger.dev/docs/documentation/concepts/http-endpoints) 
- Read our [SDK reference docs](https://trigger.dev/docs/sdk/http-endpoint)
- Check out our simple [Cal.com example](https://github.com/triggerdotdev/api-reference/blob/main/src/cal-http-endpoint.ts). This is a simple implementation.
- Check out our [WhatsApp example](https://github.com/triggerdotdev/api-reference/blob/main/src/whatsapp-http-endpoint.ts). This is a more advanced implementation (using `respondWith`) because WhatsApp sends a verification GET request to confirm before the webhooks can be created. Most APIs don't required this.

### Requirements:

- Use the structure of our [Cal.com example](https://github.com/triggerdotdev/api-reference/blob/main/src/cal-http-endpoint.ts).
- The example must connect to Zapier, receive a payload which triggers an HTTP Trigger, and then perform a simple job.

### Guidelines:

- The code must use TypeScript
- The job must use an HTTP Trigger
- Create a TypeScript type for the webhook, ideally use types from the official SDK from the API.
- Cast the json to that type using `const body = await request.json() as WebhookPayload` 
- Use native fetch where no official SDK or incompatible auth
- Avoid external packages apart from official SDKs
- Prefer REST over GraphQL - avoid raw queries
- Use a minimal `io.runTask()` callback - initialise clients and auth in global scope if possible
- Leave clear comments with links to relevant developer docs, API key pages etc. 

### Required structure:

1. Follow [this guide](https://github.com/triggerdotdev/api-reference#setup-how-to-use-this-repo) to get the project setup.​

2. Create a new file in the src folder, named to match the API, with '-http-endpoint' at the end (e.g. GitHub would be called `github-http-endpoint.ts`).​

3. The Trigger.dev client must be defined at the top of the job, with the 'api-reference' id:

```ts
const client = new TriggerClient({ id: "api-reference" });
```
​
4. You must add the Express specific lines to the bottom of the Job file:
​
```ts
// These lines can be removed if you don't want to use express
import { createExpressServer } from "@trigger.dev/express";
createExpressServer(client);
```
​
5. You must add the new script to the package.json file, in this format:
​
```ts
"scripts": {
  //..other scripts
  "<api-name>": "nodemon --watch src/<api name>.ts -r tsconfig-paths/register -r dotenv/config src/<api name>.ts"
}
```
> [!IMPORTANT]
You must test this Job works before submitting your PR, including a video or screenshot of a successful run. This may involve you having to setup accounts with services.
>

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #96 

# Docs

While zapier not does anything by default for authenticating requests, I've added two checks:
- check user-agent header by Zapier to contain Zapier
- If someone uses basic auth with Zapier, added the optional check for that
   - note that this check should kick in if the envs are present or the authorization header is present in the request

# Screen Recording

https://github.com/triggerdotdev/api-reference/assets/46300090/20d73187-5ee6-49ca-9562-20836d48ff21

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
@D-K-P 

Added the documentation.

**Comment by rishi-raj-jain** [comment]
@D-K-P 

Done

**Comment by rishi-raj-jain** [comment]
https://github.com/triggerdotdev/api-reference/assets/46300090/9613e4fe-3f2b-4385-b9e8-4679d34eec55

**Comment by rishi-raj-jain** [comment]
If possible, would love a tip on this one.

**Comment by D-K-P** [comment]
Thanks @rishi-raj-jain, this is better but can we clean up the code a bit:

- `randomHeader` isn't a great name to use - it shouldn't be random
- You don't need the authorisation steps from before
- You can make your if statements much simpler by doing something like the following:

```ts
const verify = async (request) => {
  const secret = process.env.ZAPIER_TRIGGER_SECRET;
​
  if (!secret) {
    return {
      success: false,
      reason: "Secret needs to be set.",
    }
  }
​
  if (secret !== request.headers.get("x-trigger-secret")) {
    return {
      success: false,
      reason: "Secret does not match.",
    }
  }
​
  return { success: true }
}
```

**Comment by rishi-raj-jain** [comment]
@D-K-P 

Do I still keep the basic auth thing?

**Comment by rishi-raj-jain** [comment]
Made the changes @D-K-P

**Pull request merged**
